# Generated by Django 4.2.7 on 2026-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Студенческий билет №'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Табельный номер'),
        ),
    ]
