# Generated by Django 4.2.7 on 2026-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_userprofile_student_id_userprofile_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='student_signed',
            field=models.BooleanField(default=False, verbose_name='Подписано студентом'),
        ),
        migrations.AddField(
            model_name='document',
            name='student_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
