# Generated by Django 3.2.25 on 2026-05-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_student_signed_document_student_signed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='applicant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер заявления'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='student_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('applicant', 'Абитуриент'), ('student', 'Студент'), ('teacher', 'Преподаватель'), ('secretary', 'Секретарь-делопроизводитель'), ('admin', 'Администратор')], default='applicant', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер студенческого'),
        ),
    ]
