# Generated by Django 3.2.25 on 2026-05-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20260522_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='applicant_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
