# Generated by Django 4.2.7 on 2026-06-17 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0007_auto_20260522_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='personal_user',
        ),
        migrations.AddField(
            model_name='document',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_docs', to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
    ]
