# Generated by Django 4.2.7 on 2026-06-17 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0008_remove_document_personal_user_document_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recipient_type',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
